spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile
  sql:
    init:
      encoding: utf-8

  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에  import.sql 실행
    defer-datasource-initialization : true

#  datasource:
##    url: jdbc:h2:mem:testdb
##    username: sa
#    sql-script-encoding: utf-8

  h2:
    console:
      enabled: true

jwt:
  issuer: issuer
  secret_key: secret_key
