# 1. 워크플로의 이름 지정
name : CI

# 2. 워크플로가 시작될 조건 지정 : develop 브랜치에 푸시할 때마다
on :
  push :
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest  # 3. 실행 환경 지정
    # 4. 실행 스텝 지정
    # uses : 지정한 레포지토리 확인, 코드에 대한 작업 실행
    steps:
      - uses: actions/checkout@v3   # checkout 작업을 v3 버전으로 실행

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew  # name : 스텝의 이름 지정
        run: chmod +x gradlew   # run : 실행할 명령어

      - name: Build with Gradle
        run: ./gradlew clean build    # gradle로 프로젝트를 빌드 이전 상태로 돌리고 다시 빌드